name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install
        
      - name: Set up Git user
        run: |
         git config --global user.email "viniroxo@gmail.com"
         git config --global user.name "Vinicius Roxo"

      - name: Build
        run: npm run build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build
          user_name: viniroxo
          user_email: viniroxo@gmail.com
