name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install
        
      - name: Set up Git user
        run: |
         git config --global user.email "viniroxo@gmail.com"
         git config --global user.name "Vinicius Roxo"

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npx gh-pages -d build --dotfiles --silent
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
